# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RR_Security_Project1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RR_Security_Project1
	
pod 'Firebase/Core'

end
